#!/bin/sh

if [ "$1" = "configure" ]; then
    if [ -e "/etc/init.d/arduieensy-extreme-feedback" ]; then
        chmod a+x /etc/init.d/arduieensy-extreme-feedback
        update-rc.d arduieensy-extreme-feedback defaults
        invoke-rc.d arduieensy-extreme-feedback start
    fi
fi
