#! /bin/bash

CONFIG_FILE=/etc/arduieensy-extreme-feedback/config
PID_FILE=/var/run/arduieensy-extreme-feedback
JAR_FILE=/var/lib/arduieensy-extreme-feedback/arduieensy-extreme-feedback.jar

source $CONFIG_FILE

case "$1" in
  start)
    start-stop-daemon --start --background --make-pidfile --pidfile $PID_FILE --exec /usr/lib/jvm/java-7-openjdk-`uname -i`/jre/bin/java -- -jar $JAR_FILE $JOB_URL 
    ;;
  restart)
    /etc/init.d/arduieensy-extreme-feedback stop
    /etc/init.d/arduieensy-extreme-feedback start
    ;;
  stop)
    sudo start-stop-daemon --stop --pidfile /var/run/arduieensy-extreme-feedback
    ;;
  *)
    echo "Usage: $0 start|stop|restart" >&2
    exit 3
    ;;
esac
